### ISSUE TITLE
こうですかね？

### ISSUE THREAD

**Issue by coal5314** [biikame/logbook#1]
2015-06-04 19:17:35,730 WARN script [logbook_async_initializer] .\script\combat\砲撃戦.あせる\combat_砲撃戦.あせる.js を実行中にエラー
java.lang.ArrayIndexOutOfBoundsException: 6
	at jdk.nashorn.internal.runtime.AccessorProperty.initGetterSetter(AccessorProperty.java:271) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.AccessorProperty.<init>(AccessorProperty.java:250) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewFieldSetter(SetMethodCreator.java:166) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewPropertySetter(SetMethodCreator.java:156) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createSetMethod(SetMethodCreator.java:122) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createGuardedInvocation(SetMethodCreator.java:78) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.findSetMethod(ScriptObject.java:1911) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1632) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:144) ~[nashorn.jar:?]
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:232) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps$L:172(<eval>:174) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$underscore.L:6$L:165(script/util/underscore.js:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps(<eval>:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.body(<eval>:28) ~[?:?]
	at logbook.scripting.CombatLogListener$$NashornJavaAdapter.body(Unknown Source) ~[?:?]
	at logbook.scripting.CombatLogProxy$AnyBodiesMethod.invoke(CombatLogProxy.java:27) ~[logbook.jar:?]
	at logbook.scripting.ScriptLoader$Script.invoke(ScriptLoader.java:128) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScript.anyBodies(ScriptLoader.java:313) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScriptCollection.anyBodies(ScriptLoader.java:437) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.body(CombatLogProxy.java:104) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.bodyAll(CombatLogProxy.java:67) [logbook.jar:?]
	at logbook.internal.BattleResultServer.reloadFiles(BattleResultServer.java:305) [logbook.jar:?]
	at logbook.internal.BattleResultServer.<init>(BattleResultServer.java:277) [logbook.jar:?]
	at logbook.internal.BattleResultServer.load(BattleResultServer.java:96) [logbook.jar:?]
	at logbook.gui.background.BackgroundInitializer.run(BackgroundInitializer.java:127) [logbook.jar:?]
2015-06-04 19:19:28,101 WARN script [main] .\script\combat\砲撃戦.あせる\combat_砲撃戦.あせる.js を実行中にエラー
java.lang.ArrayIndexOutOfBoundsException: 6
	at jdk.nashorn.internal.runtime.AccessorProperty.initGetterSetter(AccessorProperty.java:271) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.AccessorProperty.<init>(AccessorProperty.java:250) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewFieldSetter(SetMethodCreator.java:166) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewPropertySetter(SetMethodCreator.java:156) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createSetMethod(SetMethodCreator.java:122) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createGuardedInvocation(SetMethodCreator.java:78) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.findSetMethod(ScriptObject.java:1911) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1632) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:144) ~[nashorn.jar:?]
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:232) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps$L:172(<eval>:174) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$underscore.L:6$L:165(script/util/underscore.js:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps(<eval>:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.body(<eval>:28) ~[?:?]
	at logbook.scripting.CombatLogListener$$NashornJavaAdapter.body(Unknown Source) ~[?:?]
	at logbook.scripting.CombatLogProxy$AnyBodiesMethod.invoke(CombatLogProxy.java:27) ~[logbook.jar:?]
	at logbook.scripting.ScriptLoader$Script.invoke(ScriptLoader.java:128) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScript.anyBodies(ScriptLoader.java:313) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScriptCollection.anyBodies(ScriptLoader.java:437) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.body(CombatLogProxy.java:104) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.bodyAll(CombatLogProxy.java:67) [logbook.jar:?]
	at logbook.internal.BattleResultServer.addNewResult(BattleResultServer.java:363) [logbook.jar:?]
	at logbook.data.context.GlobalContext.doBattleresult(GlobalContext.java:1210) [logbook.jar:?]
	at logbook.data.context.GlobalContext.updateContext(GlobalContext.java:720) [logbook.jar:?]
	at logbook.server.proxy.ReverseProxyServlet$1.run(ReverseProxyServlet.java:148) [logbook.jar:?]
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source) [swt.jar:?]
	at logbook.gui.ApplicationMain.open(ApplicationMain.java:402) [logbook.jar:?]
	at logbook.gui.WindowBase.restore(WindowBase.java:865) [logbook.jar:?]
	at logbook.gui.ApplicationMain.restore(ApplicationMain.java:1259) [logbook.jar:?]
	at logbook.gui.ApplicationMain.main(ApplicationMain.java:370) [logbook.jar:?]
2015-06-04 19:42:33,916 WARN script [main] .\script\combat\砲撃戦.あせる\combat_砲撃戦.あせる.js を実行中にエラー
java.lang.ArrayIndexOutOfBoundsException: 6
	at jdk.nashorn.internal.runtime.AccessorProperty.initGetterSetter(AccessorProperty.java:271) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.AccessorProperty.<init>(AccessorProperty.java:250) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewFieldSetter(SetMethodCreator.java:166) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewPropertySetter(SetMethodCreator.java:156) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createSetMethod(SetMethodCreator.java:122) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createGuardedInvocation(SetMethodCreator.java:78) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.findSetMethod(ScriptObject.java:1911) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1632) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:144) ~[nashorn.jar:?]
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:232) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps$L:172(<eval>:174) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$underscore.L:6$L:165(script/util/underscore.js:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps(<eval>:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.body(<eval>:28) ~[?:?]
	at logbook.scripting.CombatLogListener$$NashornJavaAdapter.body(Unknown Source) ~[?:?]
	at logbook.scripting.CombatLogProxy$AnyBodiesMethod.invoke(CombatLogProxy.java:27) ~[logbook.jar:?]
	at logbook.scripting.ScriptLoader$Script.invoke(ScriptLoader.java:128) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScript.anyBodies(ScriptLoader.java:313) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScriptCollection.anyBodies(ScriptLoader.java:437) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.body(CombatLogProxy.java:104) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.bodyAll(CombatLogProxy.java:67) [logbook.jar:?]
	at logbook.internal.BattleResultServer.addNewResult(BattleResultServer.java:363) [logbook.jar:?]
	at logbook.data.context.GlobalContext.doBattleresult(GlobalContext.java:1210) [logbook.jar:?]
	at logbook.data.context.GlobalContext.updateContext(GlobalContext.java:720) [logbook.jar:?]
	at logbook.server.proxy.ReverseProxyServlet$1.run(ReverseProxyServlet.java:148) [logbook.jar:?]
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source) [swt.jar:?]
	at logbook.gui.ApplicationMain.open(ApplicationMain.java:402) [logbook.jar:?]
	at logbook.gui.WindowBase.restore(WindowBase.java:865) [logbook.jar:?]
	at logbook.gui.ApplicationMain.restore(ApplicationMain.java:1259) [logbook.jar:?]
	at logbook.gui.ApplicationMain.main(ApplicationMain.java:370) [logbook.jar:?]
2015-06-04 19:44:08,388 WARN script [main] .\script\combat\砲撃戦.あせる\combat_砲撃戦.あせる.js を実行中にエラー
java.lang.ArrayIndexOutOfBoundsException: 6
	at jdk.nashorn.internal.runtime.AccessorProperty.initGetterSetter(AccessorProperty.java:271) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.AccessorProperty.<init>(AccessorProperty.java:250) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewFieldSetter(SetMethodCreator.java:166) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewPropertySetter(SetMethodCreator.java:156) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createSetMethod(SetMethodCreator.java:122) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createGuardedInvocation(SetMethodCreator.java:78) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.findSetMethod(ScriptObject.java:1911) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1632) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:144) ~[nashorn.jar:?]
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:232) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps$L:172(<eval>:174) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$underscore.L:6$L:165(script/util/underscore.js:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps(<eval>:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.body(<eval>:28) ~[?:?]
	at logbook.scripting.CombatLogListener$$NashornJavaAdapter.body(Unknown Source) ~[?:?]
	at logbook.scripting.CombatLogProxy$AnyBodiesMethod.invoke(CombatLogProxy.java:27) ~[logbook.jar:?]
	at logbook.scripting.ScriptLoader$Script.invoke(ScriptLoader.java:128) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScript.anyBodies(ScriptLoader.java:313) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScriptCollection.anyBodies(ScriptLoader.java:437) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.body(CombatLogProxy.java:104) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.bodyAll(CombatLogProxy.java:67) [logbook.jar:?]
	at logbook.internal.BattleResultServer.addNewResult(BattleResultServer.java:363) [logbook.jar:?]
	at logbook.data.context.GlobalContext.doBattleresult(GlobalContext.java:1210) [logbook.jar:?]
	at logbook.data.context.GlobalContext.updateContext(GlobalContext.java:720) [logbook.jar:?]
	at logbook.server.proxy.ReverseProxyServlet$1.run(ReverseProxyServlet.java:148) [logbook.jar:?]
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source) [swt.jar:?]
	at logbook.gui.ApplicationMain.open(ApplicationMain.java:402) [logbook.jar:?]
	at logbook.gui.WindowBase.restore(WindowBase.java:865) [logbook.jar:?]
	at logbook.gui.ApplicationMain.restore(ApplicationMain.java:1259) [logbook.jar:?]
	at logbook.gui.ApplicationMain.main(ApplicationMain.java:370) [logbook.jar:?]
2015-06-04 19:45:19,763 WARN script [main] .\script\combat\砲撃戦.あせる\combat_砲撃戦.あせる.js を実行中にエラー
java.lang.ArrayIndexOutOfBoundsException: 6
	at jdk.nashorn.internal.runtime.AccessorProperty.initGetterSetter(AccessorProperty.java:271) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.AccessorProperty.<init>(AccessorProperty.java:250) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewFieldSetter(SetMethodCreator.java:166) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewPropertySetter(SetMethodCreator.java:156) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createSetMethod(SetMethodCreator.java:122) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createGuardedInvocation(SetMethodCreator.java:78) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.findSetMethod(ScriptObject.java:1911) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1632) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:144) ~[nashorn.jar:?]
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:232) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps$L:172(<eval>:174) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$underscore.L:6$L:165(script/util/underscore.js:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps(<eval>:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.body(<eval>:28) ~[?:?]
	at logbook.scripting.CombatLogListener$$NashornJavaAdapter.body(Unknown Source) ~[?:?]
	at logbook.scripting.CombatLogProxy$AnyBodiesMethod.invoke(CombatLogProxy.java:27) ~[logbook.jar:?]
	at logbook.scripting.ScriptLoader$Script.invoke(ScriptLoader.java:128) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScript.anyBodies(ScriptLoader.java:313) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScriptCollection.anyBodies(ScriptLoader.java:437) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.body(CombatLogProxy.java:104) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.bodyAll(CombatLogProxy.java:67) [logbook.jar:?]
	at logbook.internal.BattleResultServer.addNewResult(BattleResultServer.java:363) [logbook.jar:?]
	at logbook.data.context.GlobalContext.doBattleresult(GlobalContext.java:1210) [logbook.jar:?]
	at logbook.data.context.GlobalContext.updateContext(GlobalContext.java:720) [logbook.jar:?]
	at logbook.server.proxy.ReverseProxyServlet$1.run(ReverseProxyServlet.java:148) [logbook.jar:?]
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source) [swt.jar:?]
	at logbook.gui.ApplicationMain.open(ApplicationMain.java:402) [logbook.jar:?]
	at logbook.gui.WindowBase.restore(WindowBase.java:865) [logbook.jar:?]
	at logbook.gui.ApplicationMain.restore(ApplicationMain.java:1259) [logbook.jar:?]
	at logbook.gui.ApplicationMain.main(ApplicationMain.java:370) [logbook.jar:?]
2015-06-04 19:46:21,508 WARN script [main] .\script\combat\砲撃戦.あせる\combat_砲撃戦.あせる.js を実行中にエラー
java.lang.ArrayIndexOutOfBoundsException: 6
	at jdk.nashorn.internal.runtime.AccessorProperty.initGetterSetter(AccessorProperty.java:271) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.AccessorProperty.<init>(AccessorProperty.java:250) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewFieldSetter(SetMethodCreator.java:166) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createNewPropertySetter(SetMethodCreator.java:156) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createSetMethod(SetMethodCreator.java:122) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.SetMethodCreator.createGuardedInvocation(SetMethodCreator.java:78) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.findSetMethod(ScriptObject.java:1911) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1632) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:144) ~[nashorn.jar:?]
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:232) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps$L:172(<eval>:174) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$underscore.L:6$L:165(script/util/underscore.js:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.getBattleHps(<eval>:172) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.body(<eval>:28) ~[?:?]
	at logbook.scripting.CombatLogListener$$NashornJavaAdapter.body(Unknown Source) ~[?:?]
	at logbook.scripting.CombatLogProxy$AnyBodiesMethod.invoke(CombatLogProxy.java:27) ~[logbook.jar:?]
	at logbook.scripting.ScriptLoader$Script.invoke(ScriptLoader.java:128) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScript.anyBodies(ScriptLoader.java:313) [logbook.jar:?]
	at logbook.scripting.ScriptLoader$TableScriptCollection.anyBodies(ScriptLoader.java:437) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.body(CombatLogProxy.java:104) [logbook.jar:?]
	at logbook.scripting.CombatLogProxy.bodyAll(CombatLogProxy.java:67) [logbook.jar:?]
	at logbook.internal.BattleResultServer.addNewResult(BattleResultServer.java:363) [logbook.jar:?]
	at logbook.data.context.GlobalContext.doBattleresult(GlobalContext.java:1210) [logbook.jar:?]
	at logbook.data.context.GlobalContext.updateContext(GlobalContext.java:720) [logbook.jar:?]
	at logbook.server.proxy.ReverseProxyServlet$1.run(ReverseProxyServlet.java:148) [logbook.jar:?]
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source) [swt.jar:?]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source) [swt.jar:?]
	at logbook.gui.ApplicationMain.open(ApplicationMain.java:402) [logbook.jar:?]
	at logbook.gui.WindowBase.restore(WindowBase.java:865) [logbook.jar:?]
	at logbook.gui.ApplicationMain.restore(ApplicationMain.java:1259) [logbook.jar:?]
	at logbook.gui.ApplicationMain.main(ApplicationMain.java:370) [logbook.jar:?]

**Comment by coal5314** [comment]
長門改99　35.6×4の検証で何度か1-1-1に出かけた物です、非常に長くなってしまいましたが・・・
